export const initialState = {
  tasks: [
    {
      id: 132523,
      title: "Check email",
      status: "newTask",
      date: "0:20h",
      bg: "#ABE9CE",
    },
    {
      id: 21235,
      title: "Compare PPC agencies and make a report for Steven",
      status: "newTask",
      date: "3:00h",
      bg: "#D8DCFF",
    },
    {
      id: 3767,
      title: "Meeting with Amanda (PR department)",
      status: "newTask",
      date: "0 : 20h",
      bg: "#ABE9CE",
    },
    {
      id: 4,
      title: "Get Patrick's approval for homepage new design",
      status: "newTask",
      date: "0:20h",
      bg: "#D8DCFF",
    },
    {
      id: 115715474,
      title: "Check email",
      status: "scheduled",
      date: "0:20h",
      bg: "#FFDFBA",
    },
    {
      id: 275414354,
      title: 'Write a blogpost "7 best strategies for SEO in 2020"',
      status: "scheduled",
      date: "3:00h",
      bg: "#FEC6B7",
    },
    {
      id: 317145,
      title: "New Ad copies for Manamaja",
      status: "scheduled",
      date: "0 : 20h",
      bg: "#D9E6A2",
    },
    {
      id: 1,
      title: "Check email",
      status: "inProgress",
      date: "0:20h",
      bg: "#FFDFBA",
    },
    {
      id: 2,
      title: "Record a video comment about last week's analytics report",
      status: "inProgress",
      date: "3:00h",
      bg: "#F2BAE1",
    },
    {
      id: 3,
      title: "Process all resumes for Content Marketer position",
      status: "inProgress",
      date: "0:45h",
      bg: "#FFDFBA",
    },
    {
      id: 12244,
      title: "Check email",
      status: "completed",
      date: "2:30h",
      bg: "#F0F0F0",
    },
    {
      id: 666442,
      title: "Weekly planning session",
      status: "completed",
      date: "3:00h",
      bg: "#F0F0F0",
    },
    {
      id: 198587185783925,
      title: "Create 5+ target audiences in Facebook for Samsung ...",
      status: "completed",
      date: "0 : 20h",
      bg: "#F0F0F0",
    },
    {
      id: 46145014405,
      title: "Check FB Banner Design and give feedback",
      status: "completed",
      date: "0 : 20h",
      bg: "#F0F0F0",
    },
    {
      id: 235562155,
      title: "Check email",
      status: "completed",
      date: "0 : 20h",
      bg: "#F0F0F0",
    },
  ],
};
export const statuses = {
  status:[
    { id: 1, name: "newTask" },
    { id: 2, name: "scheduled" },
    { id: 3, name: "inProgress" },
    { id: 4, name: "completed" },
    ]
}
